'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DEARS.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to USE [AcademicResultsDB]
        '''
        '''
        '''INSERT INTO dbo.TuitionTypes(Id, NameEnglish, NameArabic)
        '''VALUES
        '''(1, N&apos;Lecture&apos;, N&apos;محاضرة&apos;),
        '''(2, N&apos;Lab&apos;,N&apos;معمل&apos;),
        '''(3, N&apos;Tutorial&apos;, N&apos;تمرين&apos;)
        '''
        '''INSERT [dbo].TimeYears (Id, NameEnglish, NameArabic)
        '''VALUES
        '''(2010, N&apos;2010/2011&apos;, N&apos;2010/2011&apos;),
        '''(2011, N&apos;2011/2012&apos;, N&apos;2011/2012&apos;),
        '''(2012, N&apos;2012/2013&apos;, N&apos;2012/2013&apos;),
        '''(2013, N&apos;2013/2014&apos;, N&apos;2013/2014&apos;),
        '''(2014, N&apos;2014/2015&apos;, N&apos;2014/2015&apos;)
        '''
        '''
        '''INSERT dbo.Semesters(Id, NameEnglish, NameArabic)
        '''VALUES 
        '''(1, N&apos;First&apos;, N&apos;الأول&apos;),        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property BasicDataQuery() As String
            Get
                Return ResourceManager.GetString("BasicDataQuery", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
