'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GPAwRecomm
	Implements IEquatable(Of GPAwRecomm)

	Function Equals1(other as GPAwRecomm) as Boolean Implements IEquatable(Of GPAwRecomm).Equals
		
		 If DirectCast(Me, Object).Equals(DirectCast(other, Object)) Then
            Return True
        Else
			If {		     Me.YearId,other.YearId,Me.GradeId,other.GradeId,Me.StudentId,other.StudentId,Me.RecommendationId,other.RecommendationId,Me.CRecommendationId,other.CRecommendationId}.Any(Function(s) s = 0) Then 
Return False
End If
		    Return (Me.YearId = other.YearId) And(Me.GradeId = other.GradeId) And(Me.StudentId = other.StudentId) And(Me.RecommendationId = other.RecommendationId) And(Me.CRecommendationId = other.CRecommendationId)
		End If	
		'Return (Me.YearId = other.YearId) And(Me.GradeId = other.GradeId) And(Me.StudentId = other.StudentId)	
	End Function
    Public Property YearId As Integer
    Public Property GradeId As Integer
    Public Property StudentId As Integer
    Public Property GPA As Decimal
    Public Property RecommendationId As Integer
    Public Property CGPA As Nullable(Of Decimal)
    Public Property CRecommendationId As Nullable(Of Integer)

    Public Overridable Property BatchEnrollment As BatchEnrollment
    Public Overridable Property Batch As Batch
    Public Overridable Property CumulativeRecommendationType As RecommendationType
    Public Overridable Property Grade As Grade
    Public Overridable Property RecommendationType As RecommendationType
    Public Overridable Property Student As Student
    Public Overridable Property TimeYear As TimeYear

End Class
