'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RecommTranslation
	Implements IEquatable(Of RecommTranslation)

	Function Equals1(other as RecommTranslation) as Boolean Implements IEquatable(Of RecommTranslation).Equals
		
		 If DirectCast(Me, Object).Equals(DirectCast(other, Object)) Then
            Return True
        Else
            Return (Me.ResText = other.ResText)
		End If	
		'Return (Me.ResText = other.ResText)	
	End Function
    Public Property ResText As String
    Public Property RecommendationTypeN As Nullable(Of Integer)

    Public Overridable Property RecommendationType As RecommendationType

End Class
