'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SemesterBatchEnrollment
	Implements IEquatable(Of SemesterBatchEnrollment)

	Function Equals1(other as SemesterBatchEnrollment) as Boolean Implements IEquatable(Of SemesterBatchEnrollment).Equals
		
		 If DirectCast(Me, Object).Equals(DirectCast(other, Object)) Then
            Return True
        Else
			If {		     Me.YearId,other.YearId,Me.GradeId,other.GradeId,Me.SemesterId,other.SemesterId,Me.StudentId,other.StudentId,Me.DisciplineId,other.DisciplineId}.Any(Function(s) s = 0) Then 
Return False
End If
		    Return (Me.YearId = other.YearId) And(Me.GradeId = other.GradeId) And(Me.SemesterId = other.SemesterId) And(Me.StudentId = other.StudentId) And(Me.DisciplineId = other.DisciplineId)
		End If	
		'Return (Me.YearId = other.YearId) And(Me.GradeId = other.GradeId) And(Me.SemesterId = other.SemesterId) And(Me.StudentId = other.StudentId)	
	End Function
    Public Property YearId As Integer
    Public Property GradeId As Integer
    Public Property SemesterId As Integer
    Public Property StudentId As Integer
    Public Property DisciplineId As Integer

    Public Overridable Property BatchEnrollment As BatchEnrollment
    Public Overridable Property CourseEnrollments As ICollection(Of CourseEnrollment) = New HashSet(Of CourseEnrollment)
    Public Overridable Property Discipline As Discipline
    Public Overridable Property Grade As Grade
    Public Overridable Property OfferedDiscipline As OfferedDiscipline
    Public Overridable Property SemesterBatch As SemesterBatch
    Public Overridable Property Semester As Semester
    Public Overridable Property Student As Student
    Public Overridable Property TimeYear As TimeYear

End Class
