'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SemesterBatch
	Implements IEquatable(Of SemesterBatch)

	Function Equals1(other as SemesterBatch) as Boolean Implements IEquatable(Of SemesterBatch).Equals
		
		 If DirectCast(Me, Object).Equals(DirectCast(other, Object)) Then
            Return True
        Else
			If {		     Me.YearId,other.YearId,Me.GradeId,other.GradeId,Me.SemesterId,other.SemesterId}.Any(Function(s) s = 0) Then 
Return False
End If
		    Return (Me.YearId = other.YearId) And(Me.GradeId = other.GradeId) And(Me.SemesterId = other.SemesterId)
		End If	
		'Return (Me.YearId = other.YearId) And(Me.GradeId = other.GradeId) And(Me.SemesterId = other.SemesterId)	
	End Function
    Public Property YearId As Integer
    Public Property GradeId As Integer
    Public Property SemesterId As Integer

    Public Overridable Property CourseDisciplines As ICollection(Of CourseDiscipline) = New HashSet(Of CourseDiscipline)
    Public Overridable Property Grade As Grade
    Public Overridable Property OfferedCourses As ICollection(Of OfferedCourse) = New HashSet(Of OfferedCourse)
    Public Overridable Property OfferedDisciplines As ICollection(Of OfferedDiscipline) = New HashSet(Of OfferedDiscipline)
    Public Overridable Property SemesterBatchEnrollments As ICollection(Of SemesterBatchEnrollment) = New HashSet(Of SemesterBatchEnrollment)
    Public Overridable Property Semester As Semester
    Public Overridable Property TimeYear As TimeYear
    Public Overridable Property Batch As Batch

End Class
