'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class AcademicResultsDBEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=AcademicResultsDBEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property BatchEnrollments() As DbSet(Of BatchEnrollment)
    Public Overridable Property Batches() As DbSet(Of Batch)
    Public Overridable Property CourseDisciplines() As DbSet(Of CourseDiscipline)
    Public Overridable Property CourseEnrollments() As DbSet(Of CourseEnrollment)
    Public Overridable Property Courses() As DbSet(Of Course)
    Public Overridable Property CourseTeachers() As DbSet(Of CourseTeacher)
    Public Overridable Property Disciplines() As DbSet(Of Discipline)
    Public Overridable Property EnrollmentTypes() As DbSet(Of EnrollmentType)
    Public Overridable Property ExamTypes() As DbSet(Of ExamType)
    Public Overridable Property GPAwRecomms() As DbSet(Of GPAwRecomm)
    Public Overridable Property Grades() As DbSet(Of Grade)
    Public Overridable Property MarksExamCWs() As DbSet(Of MarksExamCW)
    Public Overridable Property OfferedCourses() As DbSet(Of OfferedCourse)
    Public Overridable Property OfferedDisciplines() As DbSet(Of OfferedDiscipline)
    Public Overridable Property RecommendationTypes() As DbSet(Of RecommendationType)
    Public Overridable Property RecommTranslations() As DbSet(Of RecommTranslation)
    Public Overridable Property SemesterBatchEnrollments() As DbSet(Of SemesterBatchEnrollment)
    Public Overridable Property SemesterBatches() As DbSet(Of SemesterBatch)
    Public Overridable Property Semesters() As DbSet(Of Semester)
    Public Overridable Property Students() As DbSet(Of Student)
    Public Overridable Property Teachers() As DbSet(Of Teacher)
    Public Overridable Property TimeYears() As DbSet(Of TimeYear)
    Public Overridable Property TuitionTypes() As DbSet(Of TuitionType)

End Class
