'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CourseTeacher
	Implements IEquatable(Of CourseTeacher)

	Function Equals1(other as CourseTeacher) as Boolean Implements IEquatable(Of CourseTeacher).Equals
		
		 If DirectCast(Me, Object).Equals(DirectCast(other, Object)) Then
            Return True
        Else
			If {Me.YearId,other.YearId,Me.GradeId,other.GradeId,Me.SemesterId,other.SemesterId,Me.CourseId,other.CourseId,Me.TeacherId,other.TeacherId,Me.TuitionTypeId,other.TuitionTypeId}.Any(Function(s) s = 0) Then 
				Return False
			End If
		    Return (Me.YearId = other.YearId) And(Me.GradeId = other.GradeId) And(Me.SemesterId = other.SemesterId) And(Me.CourseId = other.CourseId) And(Me.TeacherId = other.TeacherId) And(Me.TuitionTypeId = other.TuitionTypeId)
		End If	
	
	End Function
    Public Property YearId As Integer
    Public Property GradeId As Integer
    Public Property SemesterId As Integer
    Public Property CourseId As Integer
    Public Property TeacherId As Integer
    Public Property TuitionTypeId As Integer

    Public Overridable Property Cours As Course
    Public Overridable Property Grade As Grade
    Public Overridable Property OfferedCours As OfferedCourse
    Public Overridable Property Semester As Semester
    Public Overridable Property Teacher As Teacher
    Public Overridable Property TimeYear As TimeYear
    Public Overridable Property TuitionType As TuitionType

End Class
