'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RecommendationType
	Implements IEquatable(Of RecommendationType)

	Function Equals1(other as RecommendationType) as Boolean Implements IEquatable(Of RecommendationType).Equals
		
		 If DirectCast(Me, Object).Equals(DirectCast(other, Object)) Then
            Return True
        Else
			If {Me.Id,other.Id}.Any(Function(s) s = 0) Then 
				Return False
			End If
		    Return (Me.Id = other.Id)
		End If	
	
	End Function
    Public Property Id As Integer
    Public Property NameArabic As String
    Public Property NameEnglish As String
    Public Property Pass As Boolean
    Public Property ShortNameEnglish As String

    Public Overridable Property GPAwRecomms As ICollection(Of GPAwRecomm) = New HashSet(Of GPAwRecomm)
    Public Overridable Property GPAwRecomms1 As ICollection(Of GPAwRecomm) = New HashSet(Of GPAwRecomm)
    Public Overridable Property RecommTranslations As ICollection(Of RecommTranslation) = New HashSet(Of RecommTranslation)

End Class
