USE [AcademicResultsDB]


INSERT INTO dbo.TuitionTypes(Id, NameEnglish, NameArabic)
VALUES
(1, N'Lecture', N'محاضرة'),
(2, N'Lab',N'معمل'),
(3, N'Tutorial', N'تمرين')

INSERT [dbo].TimeYears (Id, NameEnglish, NameArabic)
VALUES
(2010, N'2010/2011', N'2010/2011'),
(2011, N'2011/2012', N'2011/2012'),
(2012, N'2012/2013', N'2012/2013'),
(2013, N'2013/2014', N'2013/2014'),
(2014, N'2014/2015', N'2014/2015')


INSERT dbo.Semesters(Id, NameEnglish, NameArabic)
VALUES 
(1, N'First', N'الأول'),
(2, N'Second', N'الثاني')


SET IDENTITY_INSERT [dbo].[Grades] ON 

INSERT [dbo].[Grades] ([Id], [NameEnglish], [NameArabic]) 
VALUES 
(1, N'First', N'الأول'),
(2, N'Second', N'الثاني'),
(3, N'Thrid', N'الثالث'),
(4, N'Fourth', N'الرابع'),
(5, N'Fifth', N'الخامس')
SET IDENTITY_INSERT [dbo].[Grades] OFF


SET IDENTITY_INSERT [dbo].[Disciplines] ON 

INSERT [dbo].[Disciplines] ([Id], [NameEnglish], [NameArabic], [NameEnglishShort], [NameArabicShort]) 
VALUES 
(1, N'Non-Specialized', N'غير متخصص', N'Non-Specilized', N'غير متخصص'),
(2, N'Electronic and Computer Systems Engineering', N'هندسة الإلكترونيات و نظم الحاسوب', N'Electronics', N'إلكترونيات'),
(3, N'Electronic Systems Software Engineering', N'هندسة برمجيات النطم الإلكترونية', N'Software', N'هندسة برمجيات'),
(4, N'Telecommunications Engineering', N'هندسة الإتصالات', N'Telecommunications', N'اتصالات'),
(5, N'Control Systems and Instrumentation', N'نظم التحكم و الإستشعار', N'Control', N'تحكم'),
(6, N'Power Systems Engineering', N'هندسة نظم القدلرة', N'Power', N'قدرة')
SET IDENTITY_INSERT [dbo].[Disciplines] OFF


DBCC CHECKIDENT ('Courses', RESEED, 0);
SET IDENTITY_INSERT [dbo].[Courses] OFF

INSERT [dbo].[Courses] ([CourseCode], [TitleEnglish], [TitleArabic]) 
VALUES 
(N'AD4101',	N'Engineering Economics',	N'الاقتصاد الهندسي'),
(N'AD4202',	N'Engineering Administration I',	N'ادارة هندسية 1'),
(N'AD5103',	N'Engineering Administration II',	N'الادارة الهندسية 2'),
(N'AR1101',	N'Arabic Language I',	N'اللغة العربية 1'),
(N'AR2201',	N'Arabic Language II',	N'اللغة العربية 2'),
(N'CE5201',	N'Environmental Engineering',	N'هندسة البيئة'),
(N'CH1101',	N'Chemistry I',	N'الكيمياء 1'),
(N'CH1102',	N'Chemistry Lab. I',	N'معمل الكيمياء 1'),
(N'CH1203',	N'Chemistry II',	N'الكيمياء 2'),
(N'CH1204',	N'Chemistry Lab. II',	N'معمل الكيمياء 2'),
(N'EC1101',	N'Introduction to Computer Systems',	N'مقدمة نظم الحاسوب'),
(N'EC1102',	N'Computer Systems Lab. I',	N'معمل نظم الحاسوب 1'),
(N'EC1203',	N'Programming Methodology',	N'منهجية برمجة الحاسوب'),
(N'EC1204',	N'Computer Systems Lab. II',	N'معمل نظم الحاسوب 2'),
(N'EC2105',	N'Principles of Digital Systems',	N'اساسيات تصميم النظم الرقمية'),
(N'EC2106',	N'Programming Abstraction',	N'تجريد البرمجة'),
(N'EC2107',	N'Computer Systems Lab III',	N'معمل نظم الحاسوب 3'),
(N'EC2112',	N'Computer Systems Lab. IV',	N'معمل نظم الحاسوب 4'),
(N'EC2208',	N'Solid State Electronics and Devices',	N'الكترونيات و نبائط الحالة الجامدة'),
(N'EC2209',	N'Computer Visualization in Engineering',	N'الرسم بالحاسوب في الهندسة'),
(N'EC2210',	N'Programming with C',	N'البرمجة بلغة C'),
(N'EC2211',	N'Principles of Digital Systems Lab.',	N'معمل اساسيات رقمية'),
(N'EC3113',	N'Digital Systems Design',	N'تصميم النظم الرقمية'),
(N'EC3114',	N'Electronics I',	N'الالكترونيات 1'),
(N'EC3115',	N'Electronics Lab. I',	N'معمل الالكترونيات 1'),
(N'EC3139',	N'Computer Systems Lab. VA',	N'معمل نظم الحاسوب 5A'),
(N'EC3140',	N'Data Structures and Alrithms',	N'الخوارزميات و هياكل البيانات'),
(N'EC3216',	N'Computer Organization and Design',	N'تصميم و منظومة الحاسوب'),
(N'EC3217',	N'Database Systems',	N'قواعد البيانات'),
(N'EC3218',	N'Digital Systems Lab.',	N'معمل نظم رقمية 1'),
(N'EC3219',	N'Computer Systems Lab. V',	N'معمل نظم حاسوب 5'),
(N'EC4120',	N'Microelectronics Technology',	N'تقنيات الالكترونيات الدقيقة'),
(N'EC4121',	N'Microprocessors and Assembly Language',	N'المعالج الدقيق و البرمجة بلغة التجميع'),
(N'EC4122',	N'Electronics II',	N'الكترونيات 2'),
(N'EC4123',	N'Electronics Lab. II',	N'معمل الالكترونيات 2'),
(N'EC4130',	N'Software Engineering',	N'هندسة البرمجيات'),
(N'EC4224',	N'Design of Microprocessor Systems',	N'تصميم نظم المعالج الدقيق'),
(N'EC4225',	N'Microprocessor and Interfacing Lab.',	N'معمل المعالج الدقيق و الاقتران'),
(N'EC4226',	N'Data Communication and Computer Networks',	N'تبادل البيانات و شبكات الحاسوب'),
(N'EC4227',	N'Operating Systems Engineering ',	N'هندسة نظم التشغيل'),
(N'EC4232',	N'Object Oriented Programming Using C++',	N'البرمجة الموجهة للغرض باستعمال لغة ++C'),
(N'EC4251',	N'Computer Systems Lab. VI',	N'معمل نظم حاسوب 6'),
(N'EC5126',	N'Data Communication and Computer Networks',	N'تبادل البيانات و شبكات الحاسوب'),
(N'EC5127',	N'Operating Systems Engineering',	N'هندسة نظم التشغيل'),
(N'EC5128',	N'Electronics III',	N'الالكترونيات 3'),
(N'EC5129',	N'Electronics Lab. III',	N'معمل الالكترونيات 3'),
(N'EC5130',	N'Software Engineering',	N'هندسة البرمجيات'),
(N'EC5142',	N'Computer Security and Disaster Recovery',	N'تامين الحاسوب و الاستعادة من الكوارث'),
(N'EC5143',	N'Introduction to Artficial Intelligence',	N'مقدمة الذكاء الاصطناعي'),
(N'EC5144',	N'Java Technolgy',	N'تقنية جافا'),
(N'EC5149',	N'Computer Systems Lab. VII',	N'معمل نظم الحاسوب 7'),
(N'EC5231',	N'Advanced Computer Architecture',	N'بنية الحاسوب المتقدمة'),
(N'EC5232',	N'Object Oriented Programming Using C++',	N'البرمجة الموجهة للغرض باستعمال لغة ++C'),
(N'EC5233',	N'Introduction to VLSI Systems',	N'مقدمة نظم التكامل الاعظم'),
(N'EC5234',	N'Computer Systems Lab. VI',	N'معمل حاسوب 6'),
(N'EC5245',	N'Neural Networks and Fuzzy Logic',	N' الشبكات العصوبية و المنطق الغامض'),
(N'EC5246',	N'Fault Tolerance Computing',	N'الحوسبة المتسامحة مع الاخطاء'),
(N'EC5247',	N'Distributed Computing',	N'الحوسبة الموزعة'),
(N'EC5248',	N'Computer Graphics and Vision',	N'رسم و صور لحاسوب'),
(N'EC5250',	N'Computer Systems Lab. VIII',	N'معمل حاسوب 8'),
(N'EE2101',	N'Introduction to Electrical Engineering',	N'مقدمة الهندسة الكهربائية'),
(N'EE2102',	N'Electrical Circuits I',	N'الدوائر الكهربية 1'),
(N'EE2103',	N'Electrical Engineering Principles Lab.',	N'معمل اساسيات الهندسة الكهربائية'),
(N'EE2204',	N'Electrical Circuits II',	N'الدوائر الكهربية 2'),
(N'EE3105',	N'Electromechanical Energy Conversion I',	N'التحويل الكهرميكانيكي للطاقة 1'),
(N'EE3106',	N'Electrical Circuits III',	N'الدوائر الكهربية 3'),
(N'EE3107',	N'Electromagnetics',	N'الكهرومغناطيسية'),
(N'EE3108',	N'Electromechanical Energy Conversion Lab. I',	N'معمل التحويل الكهروميكانيكي للطاقة و القدرة 1'),
(N'EE3209',	N'Power Systems I',	N'نظم القدرة 1'),
(N'EE3221',	N'Electrical Engineering Elements',	N'عناصر الهندسة الكهربائية'),
(N'EE4110',	N'Computer Aided Analysis of Electrical Circuits',	N'تحليل الدوائر الكهربية باستعنال الحاسوب'),
(N'EE4211',	N'Electromagnetic Theory and Applications',	N'نظرية الكهرومغناطيسية و التطبيقات'),
(N'EE4212',	N'Power Systems II',	N'نظم قدرة 2'),
(N'EE4213',	N'Electromechanical Energy Conversion Lab II',	N'معمل تحويل كهروميكانيكي 2'),
(N'EE5114',	N'Analysis of Power Systems',	N'تحليل نظم القدرة'),
(N'EE5115',	N'Power Electronics',	N'الكترونيات القدرة'),
(N'EE5116',	N'High Voltage Engineering and Protection',	N'الجهد العالي و الحماية'),
(N'EE5117',	N'Electromechanical Energy Conversion Lab III',	N'معمل التحويل الكهروميكانيكي للطاقة و القدرة 3'),
(N'EE5218',	N'Electrical Machines Dynamics',	N'دينامية الماكينات الكهربائية'),
(N'EE5219',	N'Operation and Reliability of Power Systems',	N'تشغيل و اعتمادية نظم القدرة'),
(N'EE5220',	N'Dispersed Generation',	N'توليد القدرة من المصادر المتجددة'),
(N'EE5221',	N'Electromechanical Energy Conversion Lab IV',	N'معمل تحويل كهروميكانيكي 4'),
(N'EM1101',	N'Mechanics and Vectors',	N'الميكانيكا و المتجهات'),
(N'EM1102',	N'Calculus',	N'الحسبان'),
(N'EM1203',	N'Linear Algebra',	N'الجبر الخطي'),
(N'EM1204',	N'Analytical Geometry ',	N'الهندسة التحليلية'),
(N'EM2105',	N'Differential Equations',	N'المعادلات التفاضلية'),
(N'EM2206',	N'Statistics and Probability',	N'الإحصاء و الإحتمالات'),
(N'EM2207',	N'Mathematical Methods',	N'الطرق الرياضية'),
(N'EM3108',	N'Numerical Techniques',	N'الطرق العددية'),
(N'EM3209',	N'Complex Variables',	N'المتغيرات المركبة'),
(N'EN1201',	N'English Language I',	N'اللغة الإنجليزية 1'),
(N'EN2201',	N'English Language II',	N'اللغة الإنجليزية 2'),
(N'IS1201',	N'Islamic Studies I',	N'الدراسات الإسلامية 1'),
(N'IS2202',	N'Islamic Studies II',	N'الدراسات الإسلامية 2'),
(N'ME2101',	N'Descriptive Geometry and Drafting',	N'الهندسة الوصفية و السم الهندسي'),
(N'ME2102',	N'Thermodynamics and Heat Transfer',	N'الديناميكة الحرارية وانتقال الحرارة'),
(N'ME2203',	N'Science and Mechanics of Eng. Materials',	N'علوم المواد الهندسية'),
(N'PH1101',	N'Physics I',	N'الفيزياء 1'),
(N'PH1102',	N'Physics Lab. I',	N'معمل الفيزياء 1'),
(N'PH1203',	N'Physics II',	N'الفيزياء 2'),
(N'PH1204',	N'Physics Lab II',	N'معمل الفيزياء 2'),
(N'PR5202',	N'Project',	N'مشروع '),
(N'SC3201',	N'Electrical Measurements and Instrumentation',	N'القياسات الكهربائية و الاجهزة'),
(N'SC3202',	N'Signals and Systems',	N'تحليل الاشارة والنظم'),
(N'SC3203',	N'Measurements Lab. I',	N'معمل القياسات'),
(N'SC4104',	N'Communications Systems I',	N'نظم الاتصالات 1'),
(N'SC4105',	N'Communications Systems Lab. I',	N'معمل الاتصالات 1'),
(N'SC4206',	N'Communications Systems II',	N'نظم اتصالات 2'),
(N'SC4207',	N'Principles of Automatic Control',	N'اسس التحكم الالي'),
(N'SC4208',	N'Digital Signal Processing',	N'معالجة الاشارة الرقمية'),
(N'SC4209',	N'Communications Systems Lab. II',	N'معمل الاتصالات 2'),
(N'SC4210',	N'Control Lab. I',	N'معمل تحكم'),
(N'SC4219',	N'Measuring Instruments and Transducers',	N'مبادئي الاجهزة الدقيقة'),
(N'SC4220',	N'Measurements Lab. II',	N'معمل قياسات 2'),
(N'SC5112',	N'Digital Communication Systems',	N'نظم الاتصالات الرقمية'),
(N'SC5113',	N'Satellite Communications Systems',	N'نظم اتصالات التوابع الاصطناعية'),
(N'SC5114',	N'Communications Systems Lab. III',	N'معمل الاتصالات 3'),
(N'SC5121',	N'Linear Control Theory',	N'نظم التحكم الخطي'),
(N'SC5122',	N'Sampled Data and Optimum Control',	N'نظم المعطيات النموذجية و التحكم الافضل'),
(N'SC5123',	N'Computer Controlled Systems',	N'التحكم بواسطة الحاسوب'),
(N'SC5124',	N'Control Lab. II',	N'هندسة تقيم الاداء'),
(N'SC5129',	N'Simulation and Modeling',	N'معمل تحكم 2'),
(N'SC5211',	N'Performance Engineering',	N'المحاكاة و النمذجة'),
(N'SC5215',	N'Fiber Optics Communications Systems',	N'نظم اتصالات الالياف البصرية'),
(N'SC5216',	N'Antennas and Wave Propagation',	N'الهوائيات و انتشار الموجات'),
(N'SC5217',	N'Switching and Traffic Theory',	N'التبديل و نظرية الحركة'),
(N'SC5218',	N'Communications Systems Lab. IV',	N'معمل اتصالات 4'),
(N'SC5225',	N'Nonlinear Control Theory',	N'نظرية التحكم اللاخطي'),
(N'SC5226',	N'Design of Control Systems',	N'تصميم نظم التحكم'),
(N'SC5227',	N'Automation of Power Stations',	N'التحكم بالمحطات الكهربائية'),
(N'SC5228',	N'Control Lab. III',	N'معمل تحكم 3'),
(N'SD1101',	N'Sudanese Studies',	N'الدراسات السودانية')

DBCC CHECKIDENT ('Teachers', RESEED, 0);
SET IDENTITY_INSERT [dbo].[Teachers] ON

INSERT dbo.Teachers (Id, NameArabic, NameEnglish)
VALUES
(1,N'سامي محمد شريف',			N'Sami Mohammad Sharif'),
(2,N'شريف فضل بابكر الفضل',			N'Sharief Fadul Babiker') ,
(3,N'محمد علي حمد عباس',			N'Mohammed Ali Hamad Abbas') ,
(4,N'الأمين حمودة دبيب',			N'Alamin Hamoda Dabib'),
(5,N'إيمان أبو المعالى عبد الرحمن',			N'Iman Abuel Maaly AbdulRahman') ,
(6,N'عبد الرحمن على كرار محمد احمد',			N'AbdalRahman Ali Karrar') ,
(7,N'كمال رمضان داؤود محمد',			N'Kamal Ramadam Dawood Mohammad') ,
(8,N'حميد عباس علي العلواني',			N'Hamid Abbas Alalawani') ,
(9,N'الفاضل زكريا',			N'Al Fadil Zakaria') ,
(10,N'غسان طه شقيدي',			N'Gassan Taha Shugaidi') ,
(11,N'نجلاء',			N'Najla') ,
(12,N'سماح محمد هاشم صديق',			N'Samah Mohammad Hashim Siddig') ,
(13,N'عزة الجيلي عبد الكريم احمد',			N'Azza Elgaili Ahmed AbdelKareem') ,
(14,N'عزة حسن محمد احمد محمد',			N'Azza Hassan Mohammad Ahmed') ,
(15,N'محمد جعفر أحمد النورانى',			N'Mohammad Gafar Elnourani') ,
(16,N'وجدان محمد الطيب احمد',			N'Wijdan Mohamad Al tayeb Ahmed') ,
(17,N'محمد عصمت عبد الحميد محمد',			N'Mohammad Esmat AbdelHamid Mohammad') ,
(18,N'احمد عبيد محمد احمد خيري',			N'Ahmed Obeid Mohammad Ahmed Kheiri') ,
(19,N'ايمان متولى عبد المجيد',			N'Iman Mutwali AbdelMajid') ,
(20,N'رانيا نعيم حاج على خلف الله',			N'Rania Naeem Hajj Ali KhalafAllah') ,
(21,N'عيسى يحي أحمد محمد',			N'Essa Yahya Ahmed Mohammad') ,
(22,N'محمد سمير سعد الدين',			N'Mohammad Samir Saad ElDeen') ,
(23,N'هبة حسن سيد محمد على امام',			N'Hiba Hassan Sayid Mohammad Ali Imam') ,
(24,N'عفراء',			N'Afraa') ,
(25,N'يوسف الحافظ',			N'Yousif Al Hafiz') ,
(26,N'أنس حسن محمد علي أبوشوك',			N'Anas Hassan Mohammad Ali Abu Shawk') ,
(27,N'عبد الكريم عبد الرحمن عبد الكريم بدرى',			N'AbdelKareem AbdelRahman AbdelKareem Bedri') ,
(28,N'شيماء سيد أحمد عوض سيد أحمد',			N'Sheima SidAhmed Awad SidAhmed') ,
(29,N'عبد الرحمن أحمد التجانى عبد الرحمن',			N'AbdelRahman Ahmed Eltigani AbdelRahman') ,
(30,N'ماريانا مجدى منير كامل',			N'Mariana Magdi Kamil Mounir') ,
(31,N'مهند احمد محمد الحسن',			N'Mohanad Ahmed Mohamed Elhassan Ahmed') ,
(32,N'مروة مأمون عبدالقادر ',			N'Marwa Mamoun Abdelgadir') ,
(33,N'أمل السماني',			N'Amel Elsamani Ahmed Taha') ,
(34,N'مؤيد الفاتح عثمان',			N'Muayed ElFatih Osman') ,
(35,N'يوسف عاصم سيد أحمد',			N'Yousif Asim SidAhmed') ,
(36,N'فايقة محمد محمد أحمد',			N'Faigah Mohammed Mohammad Ahmed') ,
(37,N'رفيدة عبد المنعم بابكر',			N'Rufaidah AbdelMoneim Babiker') 
SET IDENTITY_INSERT [dbo].[Teachers] OFF


INSERT [dbo].[ExamTypes] ([Id], [NameArabic], [NameEnglish]) 
VALUES 
(1, N'النظامي', N'Regular'),
(2, N'ملاحق و بديل', N'Subs/Supp')

INSERT [dbo].[EnrollmentTypes] ([Id], NameArabic, [NameEnglish]) 
VALUES 
(1, N'نظامي', N'Regular'),
(2, N'تحويل', N'Transfer'),
(3, N'خارجي', N'External'),
(4, N'إعادة', N'Repeat'),
(5, N'إعادة جلوس', N'Resit')

INSERT [dbo].[RecommendationTypes] ([Id], NameArabic, NameEnglish, [ShortNameEnglish], [Pass]) 
VALUES 
(1, N'مرتبة الشرف اللأولى', N'First Degree Honour', N'I', 1),
(17, N'مرتبة الشرف الثانية', N'Second Degree Honour', N'II', 1),
(2, N'مرتبة الشرف الثانية - القسم الأول', N'Second Degree Honour - First Division', N'II-1', 1),
(3, N'مرتبة الشرف الثانية - القسم الثاني', N'Second Degree Honour - Second Division', N'II-2', 1),
(4, N'مرتبة الشرف الثالثة', N'Third Degree Honour', N'III', 1),
(5, N'نجاح', N'Passed', N'Passed', 1),
(6, N'إعادة', N'Repeat', N'Repeat', 0),
(7, N'رسوب', N'Failed', N'Failed', 0),
(8, N'بديل', N'Substitutes', N'Subs', 0),
(9, N'ملحق', N'Supplementary', N'Supp.', 0),
(10, N'بديل\ملحق', N'Substitute/Supplementary', N'Subs./Supp.', 0),
(11, N'إعادة جلوس', N'Resit', N'Resit', 0),
(12, N'معدل ضعيف', N'Weak GPA', N'WGPA', 0),
(13, N'حالة خاصة', N'Special Case', N'Special Case', 0),
(14, N'تجميد', N'Suspend', N'Suspend', 0),
(15, N'فصل', N'Dismiss', N'Dismiss', 0),
(16, N'عام بديل', N'Substitute Year', N'Sub. Year', 0)


INSERT [dbo].[RecommTranslations] ([ResText], [RecommendationTypeN])
VALUES 
(N'A', 13),
(N'I', 1),
(N'II-1', 2),
(N'II-2', 3),
(N'III', 4),
(N'III-WGPA', 12),
(N'Resit 1', 11),
(N'Resit 2', 11),
(N'Resit 4', 11),
(N'S', 9),
(N'WGPA', 12),
(N'WGPA - ملحق 4', 12),
(N'إعادة', 6),
(N'إعادة جلوس', 11),
(N'إعادة جلوس 1', 11),
(N'إعادة جلوس 2', 11),
(N'إعادة جلوس 3', 11),
(N'اعادة', 6),
(N'اعادة جلوس 2', 11),
(N'بديل', 8),
(N'بديل 1', 8),
(N'بديل 1 + ملحق 2', 10),
(N'بديل 1 + ملحق 4', 10),
(N'بديل 1 ملحق 1', 10),
(N'بديل 2', 8),
(N'بديل 3', 8),
(N'بديل 4', 8),
(N'بديل 4 الدور الثاني', 8),
(N'بديل 4 ملحق 1', 10),
(N'بديل+4 ملحق', 10),
(N'تجميد', 14),
(N'حالة خاصة', 13),
(N'رسوب', 7),
(N'سنة بديلة', 16),
(N'عام بديل', 16),
(N'عام دراسي بديل', 16),
(N'فصل', 15),
(N'ملحق 1', 9),
(N'ملحق 1 + بديل 1', 10),
(N'ملحق 1 + بديل 4', 10),
(N'ملحق 1 + بديل 8', 10),
(N'ملحق 1 + فصل دراسي بديل', 10),
(N'ملحق 1 بديل 8', 10),
(N'ملحق 10', 9),
(N'ملحق 12', 9),
(N'ملحق 14', 9),
(N'ملحق 16', 9),
(N'ملحق 2', 9),
(N'ملحق 2 + بديل 2', 10),
(N'ملحق 2 + بديل 5', 10),
(N'ملحق 2 + بديل 6', 10),
(N'ملحق 3', 9),
(N'ملحق 3 + بديل 1', 10),
(N'ملحق 3 + بديل 4', 10),
(N'ملحق 3 بديل 1', 10),
(N'ملحق 4', 9),
(N'ملحق 4 + بديل 1', 10),
(N'ملحق 4 + بديل 2', 10),
(N'ملحق 4 + بديل 3', 10),
(N'ملحق 4 بديل 1', 10),
(N'ملحق 4 بديل 2', 10),
(N'ملحق 5', 9),
(N'ملحق 5 + بديل 1', 10),
(N'ملحق 5 + بديل 2', 10),
(N'نجاح', 5)